In [1]:
import torch, torchvision
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

[Torch has so many activation functions](https://pytorch.org/docs/stable/nn.html#non-linear-activations-weighted-sum-nonlinearity) and they are constantly adding to it. Below are a couple of the popular ones written out via their documentation.

In [2]:
import torch.nn as nn
# input = torch.randn(1)
# input = torch.tensor([152.89])
# input = torch.tensor([250.])
input = torch.tensor([-152.89])

m = nn.ReLU()
output = m(input)
print(input, output)

tensor([-152.8900]) tensor([0.])


In [3]:
m = nn.LeakyReLU(0.1)
output = m(input)
print(input, output)

tensor([-152.8900]) tensor([-15.2890])


In [4]:
m = nn.Sigmoid()
output = m(input)
print(input, output)

tensor([-152.8900]) tensor([0.])


In [5]:
m = nn.Tanh()
output = m(input)
print(input, output)

tensor([-152.8900]) tensor([-1.])


In [6]:
m = nn.Softmax(dim=0)
output = m(input)
print(input, output)

tensor([-152.8900]) tensor([1.])


Point being, activation function choice has a huge impact and as Josh covered, they each have pros and cons. For example, when you have inputs that range from 0-255 (color pixels) you can get away with functions like ReLU that don't care about negative numbers and have better results that differentiate better than things like sigmoid and tanh between 255 and 250.